backend:
  name: github
  repo: bshir/kidsvoice # Path to your Github repository
  branch: master
  site_domain: kidsvoice.netlify.com
  publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "resource"
    label: "Resource"
    folder: "content/resource"
    create: true
    # slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Type", name: "type", widget: "string"}
      - {label: "categories", name: "categories", widget: "list"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Card Background Color", name: "cardbackground", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}